version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:16.8.0-browsers

jobs:
  js-tests:
    parameters:
      php-version:
        type: string
    executor:
      name: node
    steps:
      - node/install-npm
      - checkout
      - node/install-packages:
      - run: npm test

workflows:
  test:
    jobs:
      - js-tests:
          filters:
            tags:
              only: /.*/
          matrix:
            parameters:
              job-number: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30' ]
